name: admin_tcc
description: "Training Empowerment Association"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  collection: ^1.19.1
  another_flushbar: ^1.12.30
  shared_preferences: ^2.2.2
  file_picker: ^10.1.9

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.9

  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Yellowtail
      fonts:
        - asset: assets/fonts/Yellowtail-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon-bg.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icon-bg.png 
  android: true
  ios: true